// Generated by GG/scripts/sync-game-menus.mjs.
export const GAME_MENU = {
  "selector": "[data-gg-pregame]",
  "steps": {
    "en": [
      "Surround territory and capture enemy stones.",
      "Tap an empty intersection to place a stone; pass when no useful move remains.",
      "Keep groups connected and protect their liberties, the empty points beside them."
    ],
    "ru": [
      "Окружай территории и захватывай камни соперника.",
      "Нажимай на пустое пересечение для хода. Пасуй, когда полезных ходов нет.",
      "Соединяй группы и защищай их дыхания — соседние пустые точки."
    ]
  }
}
